name: EmoChar
options:
  bundleIdPrefix: de.marc
  deploymentTarget:
    macOS: "13.0"
targets:
  EmoChar:
    type: application
    platform: macOS
    sources:
      - src
    info:
      path: src/Info.plist
      properties:
        CFBundleName: EmoChar
        CFBundleDisplayName: EmoChar
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
        LSMinimumSystemVersion: "13.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.marc.EmoChar
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: NO
